# Generated by Django 4.0.3 on 2022-04-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='categories',
        ),
    ]
