# Generated by Django 4.0.3 on 2022-04-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jogo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='image',
        ),
    ]
