# Generated by Django 4.0.3 on 2022-04-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='categories',
        ),
        migrations.AddField(
            model_name='jogo',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='core.category'),
        ),
    ]
