# Generated by Django 4.0.3 on 2022-04-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_jogo_categories_jogo_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='categories',
            field=models.ManyToManyField(to='core.category'),
        ),
    ]
