# Generated by Django 4.0.3 on 2022-04-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_jogo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='link_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
