# Generated by Django 4.0.3 on 2022-04-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_jogo_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
