# Generated by Django 4.0.3 on 2022-04-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_category_jogo_jogo_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
