# Generated by Django 4.0.3 on 2022-04-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jogo_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
