# Generated by Django 4.0.3 on 2022-04-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_jogo_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
