# Generated by Django 4.0.3 on 2022-04-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_jogo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='storage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
